/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.io.IOException;
import javax.swing.JFrame;
import niti.ServerskaNit;

/**
 *
 * @author Vanja Vlahović
 */
public class FMainForm extends javax.swing.JFrame {

    private ServerskaNit serverskaNit;
    
    /**
     * Creates new form FMainForm
     */
    public FMainForm() {
        initComponents();
        setLocationRelativeTo(null);
        jBtnPokreni.setEnabled(false);
        jBtnZaustavi.setEnabled(false);
        jLblStatus.setText("Server nije pokrenut");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnPokreni = new javax.swing.JButton();
        jBtnZaustavi = new javax.swing.JButton();
        jLblStatus = new javax.swing.JLabel();
        jBtnProveri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setResizable(false);

        jBtnPokreni.setText("Pokreni server");
        jBtnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPokreniActionPerformed(evt);
            }
        });

        jBtnZaustavi.setText("Zaustavi server");
        jBtnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZaustaviActionPerformed(evt);
            }
        });

        jLblStatus.setFont(new java.awt.Font("Rod", 0, 14)); // NOI18N

        jBtnProveri.setText("Proveri parametre baze");
        jBtnProveri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProveriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnProveri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnZaustavi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jBtnProveri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPokreni)
                    .addComponent(jBtnZaustavi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPokreniActionPerformed
        if (serverskaNit == null || !serverskaNit.isAlive()) {
            try {
                serverskaNit = new ServerskaNit();
                serverskaNit.start();

                jBtnPokreni.setEnabled(false);
                jBtnZaustavi.setEnabled(true);
                jBtnProveri.setEnabled(false);
                
                jLblStatus.setText("Server je pokrenut");

            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        } else {
            System.err.println("Serverska nit je vec pokrenuta");
        }
    }//GEN-LAST:event_jBtnPokreniActionPerformed

    private void jBtnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZaustaviActionPerformed
        try {
            if (serverskaNit.getServerSocket() != null && serverskaNit.getServerSocket().isBound()) {
                serverskaNit.getServerSocket().close();
                
                jBtnPokreni.setEnabled(true);
                jBtnZaustavi.setEnabled(false);
                jBtnProveri.setEnabled(true);
                
                jLblStatus.setText("Server je zaustavljen");
            }
        } catch (IOException ex) {
            System.err.println("Serverska nit je vec prekinuta");
        }
    }//GEN-LAST:event_jBtnZaustaviActionPerformed

    private void jBtnProveriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProveriActionPerformed
        new FKonfiguracija(this, true, jBtnPokreni).setVisible(true);
    }//GEN-LAST:event_jBtnProveriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPokreni;
    private javax.swing.JButton jBtnProveri;
    private javax.swing.JButton jBtnZaustavi;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
