/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Proizvod;
import domain.TipProizvoda;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanja Vlahović
 */
public class FDodajProizvod extends javax.swing.JFrame {

    private Long sifraProizvoda;
    List<TipProizvoda> tipovi;

    /**
     * Creates new form FDodajProizvod
     */
    public FDodajProizvod() {
        initComponents();
        try {
            tipovi = Controller.getInstance().vratiTipoveProizvoda();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        popuniFormu();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtSifra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtCena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtProizvodjac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCBVelicina = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jCBTipovi = new javax.swing.JComboBox();
        jBtnSacuvaj = new javax.swing.JButton();
        jBtnDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodavanje novog proizvoda");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Proizvod"));

        jLabel1.setText("Šifra proizvoda:");

        jTxtSifra.setEnabled(false);

        jLabel2.setText("Naziv:");

        jLabel3.setText("Cena:");

        jLabel4.setText("Proizvođač:");

        jLabel5.setText("Veličina:");

        jCBVelicina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Tip proizvoda:");

        jCBTipovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBtnSacuvaj.setText("Sacuvaj");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jBtnDodaj.setText("Dodaj novi");
        jBtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxtSifra)
                    .addComponent(jTxtNaziv)
                    .addComponent(jTxtCena)
                    .addComponent(jTxtProizvodjac)
                    .addComponent(jCBVelicina, 0, 248, Short.MAX_VALUE)
                    .addComponent(jCBTipovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCBVelicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCBTipovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSacuvaj)
                    .addComponent(jBtnDodaj))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed
        try {
            Proizvod proizvod = validacija();
            String poruka = Controller.getInstance().sacuvajProizvod(proizvod);
            JOptionPane.showMessageDialog(this, poruka);
            jBtnDodaj.setEnabled(true);
            jBtnSacuvaj.setEnabled(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    private void jBtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajActionPerformed
        resetujFormu();
        jBtnSacuvaj.setEnabled(true);
        jBtnDodaj.setEnabled(false);
    }//GEN-LAST:event_jBtnDodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDodaj;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JComboBox jCBTipovi;
    private javax.swing.JComboBox jCBVelicina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCena;
    private javax.swing.JTextField jTxtNaziv;
    private javax.swing.JTextField jTxtProizvodjac;
    private javax.swing.JTextField jTxtSifra;
    // End of variables declaration//GEN-END:variables

    private void popuniFormu() {
        jBtnDodaj.setEnabled(false);
        try {
            Long proizvodID = Controller.getInstance().kreirajNovProizvod();
            sifraProizvoda = proizvodID;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            dispose();
        }
        jTxtSifra.setText(sifraProizvoda + "");
        jCBVelicina.removeAllItems();
        jCBTipovi.removeAllItems();
        jCBVelicina.addItem("0.33");
        jCBVelicina.addItem("0.5");
        jCBVelicina.addItem("0.7");

        for (TipProizvoda tip : tipovi) {
            jCBTipovi.addItem(tip);
        }

    }

    private Proizvod validacija() throws Exception {
        String naziv = jTxtNaziv.getText();
        String cena = jTxtCena.getText();
        String proizvodjac = jTxtProizvodjac.getText();
        if (naziv.isEmpty() || cena.isEmpty() || proizvodjac.isEmpty()) {
            throw new Exception("Sva polja moraju biti uneta!");
        }
        BigDecimal cenaD;
        try {
            cenaD = new BigDecimal(cena.trim());
        } catch (NumberFormatException e) {
            throw new Exception("Cena mora biti uneta u formatu broja!");
        }
        String velicina = (String) jCBVelicina.getSelectedItem();
        TipProizvoda tip = (TipProizvoda) jCBTipovi.getSelectedItem();

        return new Proizvod(sifraProizvoda, naziv, cenaD, proizvodjac, velicina, tip);
    }

    private void resetujFormu() {
        try {
            Long proizvodID = Controller.getInstance().kreirajNovProizvod();
            sifraProizvoda = proizvodID;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            dispose();
        }
        jTxtSifra.setText(sifraProizvoda + "");
        jTxtNaziv.setText("");
        jTxtCena.setText("");
        jTxtProizvodjac.setText("");
    }
}
