/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vanja Vlahović
 */
public class FGlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form FGlavnaForma
     */
    public FGlavnaForma() {
        initComponents();
        try {
            jLblKonobar.setText(Controller.getInstance().getKonobar().toString());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblKonobar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnKreirajRacun = new javax.swing.JButton();
        jBtnPretraziRacune = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBtnNovProizvod = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtnPretraziRezervacije = new javax.swing.JButton();
        jBtnKreirajRezervaciju = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIDodajProizvod = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIKreirajRacun = new javax.swing.JMenuItem();
        jMIPretraziRacune = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIKreirajRezervaciju = new javax.swing.JMenuItem();
        jMIPretraziRezervacije = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Splav sudbina");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Upravljanje računima"));

        jBtnKreirajRacun.setText("Kreiraj račun");
        jBtnKreirajRacun.setPreferredSize(new java.awt.Dimension(100, 25));
        jBtnKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKreirajRacunActionPerformed(evt);
            }
        });

        jBtnPretraziRacune.setText("Pretraži račune");
        jBtnPretraziRacune.setPreferredSize(new java.awt.Dimension(100, 25));
        jBtnPretraziRacune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPretraziRacuneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jBtnKreirajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnPretraziRacune, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnKreirajRacun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnPretraziRacune, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Upravljanje proizvodima"), "Upravljanje proizvodima"));

        jBtnNovProizvod.setText("Dodaj nov proizvod");
        jBtnNovProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovProizvodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnNovProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnNovProizvod, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Upravljanje rezervacijama"));

        jBtnPretraziRezervacije.setText("Pretraži rezervacije");
        jBtnPretraziRezervacije.setPreferredSize(new java.awt.Dimension(100, 25));
        jBtnPretraziRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPretraziRezervacijeActionPerformed(evt);
            }
        });

        jBtnKreirajRezervaciju.setText("Kreiraj rezervaciju");
        jBtnKreirajRezervaciju.setPreferredSize(new java.awt.Dimension(100, 25));
        jBtnKreirajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKreirajRezervacijuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jBtnKreirajRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jBtnPretraziRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnKreirajRezervaciju, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jBtnPretraziRezervacije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Uradi");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMIDodajProizvod.setText("Dodaj proizvod");
        jMIDodajProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDodajProizvodActionPerformed(evt);
            }
        });
        jMenu1.add(jMIDodajProizvod);

        jMenu3.setText("Račun");

        jMIKreirajRacun.setText("Kreiraj račun");
        jMIKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIKreirajRacunActionPerformed(evt);
            }
        });
        jMenu3.add(jMIKreirajRacun);

        jMIPretraziRacune.setText("Pretraži račune");
        jMIPretraziRacune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPretraziRacuneActionPerformed(evt);
            }
        });
        jMenu3.add(jMIPretraziRacune);

        jMenu1.add(jMenu3);

        jMenu4.setText("Rezervacija");

        jMIKreirajRezervaciju.setText("Kreiraj rezervaciju");
        jMIKreirajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIKreirajRezervacijuActionPerformed(evt);
            }
        });
        jMenu4.add(jMIKreirajRezervaciju);

        jMIPretraziRezervacije.setText("Pretraži rezervacije");
        jMIPretraziRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPretraziRezervacijeActionPerformed(evt);
            }
        });
        jMenu4.add(jMIPretraziRezervacije);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informacije");

        jMenuItem7.setText("O aplikaciji");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLblKonobar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblKonobar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPretraziRacuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPretraziRacuneActionPerformed
        new FPretragaRacuna().setVisible(true);
    }//GEN-LAST:event_jBtnPretraziRacuneActionPerformed

    private void jBtnNovProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovProizvodActionPerformed
        try {
            kreirajProizvod();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnNovProizvodActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        try {
            kreirajProizvod();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jBtnKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKreirajRacunActionPerformed
        try {
            kreirajRacun();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnKreirajRacunActionPerformed

    private void jBtnKreirajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKreirajRezervacijuActionPerformed
        try {
            kreirajRezervaciju();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnKreirajRezervacijuActionPerformed

    private void jBtnPretraziRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPretraziRezervacijeActionPerformed
        new FPretragaRezervacija().setVisible(true);
    }//GEN-LAST:event_jBtnPretraziRezervacijeActionPerformed

    private void jMIDodajProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDodajProizvodActionPerformed
        try {
            kreirajProizvod();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMIDodajProizvodActionPerformed

    private void jMIKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIKreirajRacunActionPerformed
        try {
            kreirajRacun();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMIKreirajRacunActionPerformed

    private void jMIPretraziRacuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPretraziRacuneActionPerformed
        new FPretragaRacuna().setVisible(true);
    }//GEN-LAST:event_jMIPretraziRacuneActionPerformed

    private void jMIKreirajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIKreirajRezervacijuActionPerformed
        try {
            kreirajRezervaciju();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMIKreirajRezervacijuActionPerformed

    private void jMIPretraziRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPretraziRezervacijeActionPerformed
        new FPretragaRezervacija().setVisible(true);
    }//GEN-LAST:event_jMIPretraziRezervacijeActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       new FInformacije(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnKreirajRacun;
    private javax.swing.JButton jBtnKreirajRezervaciju;
    private javax.swing.JButton jBtnNovProizvod;
    private javax.swing.JButton jBtnPretraziRacune;
    private javax.swing.JButton jBtnPretraziRezervacije;
    private javax.swing.JLabel jLblKonobar;
    private javax.swing.JMenuItem jMIDodajProizvod;
    private javax.swing.JMenuItem jMIKreirajRacun;
    private javax.swing.JMenuItem jMIKreirajRezervaciju;
    private javax.swing.JMenuItem jMIPretraziRacune;
    private javax.swing.JMenuItem jMIPretraziRezervacije;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void kreirajRezervaciju() throws IOException, Exception {
        Long rezervacijaID = Controller.getInstance().kreirajNovuRezervaciju();
        FRezervacija f = new FRezervacija(rezervacijaID);
        f.setVisible(true);
        JOptionPane.showMessageDialog(f,"Sistem je kreirao rezervaciju!");
    }

    private void kreirajRacun() throws IOException, Exception {
        Long racunID = Controller.getInstance().kreirajNovRacun();
        FRacun f = new FRacun(racunID);
        f.setVisible(true);
        JOptionPane.showMessageDialog(f,"Sistem je kreirao račun!");
    }

    private void kreirajProizvod() throws IOException, Exception {
        FDodajProizvod f = new FDodajProizvod();
        f.setVisible(true);
        JOptionPane.showMessageDialog(f,"Sistem je kreirao proizvod!");
    }

}
