/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import domain.Rezervacija;
import domain.Status;
import domain.Sto;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.component.table.model.StoTableModel;

/**
 *
 * @author Vanja Vlahović
 */
public class FRezervacija extends javax.swing.JFrame {
    
    private StoTableModel model;
    private final Long sifraRezervacije;
    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
    private final String mode;

    /**
     * Creates new form FRezervacija
     */
    public FRezervacija(Long sifraRezervacije) {
        initComponents();
        this.sifraRezervacije = sifraRezervacije;
        mode = "new";
        popuniFormu();
        setLocationRelativeTo(null);
    }
    
    FRezervacija(Rezervacija r) {
        initComponents();
        this.sifraRezervacije = r.getSifra();
        mode = "edit";
        popuniFormu(r);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtVreme = new javax.swing.JTextField();
        jTxtSifra = new javax.swing.JTextField();
        jTxtNaIme = new javax.swing.JTextField();
        jTxtBrojMesta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaNapomena = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnDodajSto = new javax.swing.JButton();
        jCBStolovi = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtStoMesto = new javax.swing.JTextField();
        jBtnIzbaciSto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTxtUkupno = new javax.swing.JTextField();
        jBtnSacuvaj = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBtnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiranje rezervacije");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezervacija"));
        jPanel1.setToolTipText("");

        jLabel1.setText("Šifra rezervacije:");

        jLabel2.setText("Na ime:");

        jLabel3.setText("Vreme (dd.MM.yyyy.):");

        jLabel4.setText("Broj mesta:");

        jLabel5.setText("Napomena:");

        jTxtSifra.setEditable(false);

        jTxtAreaNapomena.setColumns(20);
        jTxtAreaNapomena.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaNapomena);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stolovi"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jBtnDodajSto.setText("Dodaj sto");
        jBtnDodajSto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDodajStoActionPerformed(evt);
            }
        });

        jCBStolovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBStolovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBStoloviActionPerformed(evt);
            }
        });

        jLabel6.setText("Sto:");

        jLabel7.setText("Broj mesta:");

        jTxtStoMesto.setEnabled(false);

        jBtnIzbaciSto.setText("Izbaci sto");
        jBtnIzbaciSto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzbaciStoActionPerformed(evt);
            }
        });

        jLabel8.setText("Ukupno: ");

        jTxtUkupno.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBStolovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtStoMesto)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIzbaciSto)
                            .addComponent(jBtnDodajSto))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBStolovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtStoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDodajSto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnIzbaciSto)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnSacuvaj.setText("Sacuvaj rezervaciju");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jButton1.setText("Učitaj slobodne stolove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBtnOdustani.setText("Odustani");
        jBtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNaIme)
                            .addComponent(jTxtBrojMesta)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jBtnOdustani)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNaIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtBrojMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSacuvaj)
                    .addComponent(jBtnOdustani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBStoloviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBStoloviActionPerformed
        Sto sto = (Sto) jCBStolovi.getSelectedItem();
        if (sto != null) {
            jTxtStoMesto.setText(sto.getBrojMesta() + "");
        }
    }//GEN-LAST:event_jCBStoloviActionPerformed

    private void jBtnDodajStoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDodajStoActionPerformed
        Sto sto = (Sto) jCBStolovi.getSelectedItem();
        try {
            model.dodajSto(sto);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        osveziUkupanBrojObezbedjenihMesta();
    }//GEN-LAST:event_jBtnDodajStoActionPerformed

    private void jBtnIzbaciStoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzbaciStoActionPerformed
        int red = jTable1.getSelectedRow();
        if (red != -1) {
            model.izbaciSto(red);
            osveziUkupanBrojObezbedjenihMesta();
        }
    }//GEN-LAST:event_jBtnIzbaciStoActionPerformed

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed
        try {
            Rezervacija rezervacija = validacija();
            if(mode.equals("edit")){
                List<Sto> obrisani = model.getObrisani();
                List<Sto> sviStolovi = new ArrayList<>();
                sviStolovi.addAll(obrisani);
                sviStolovi.addAll(rezervacija.getStolovi());
                rezervacija.setStolovi(sviStolovi);
            }
            Controller.getInstance().sacuvajRezervaciju(rezervacija);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio rezervaciju!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Date vreme = new Date();
        jCBStolovi.removeAllItems();
        try {
            vreme = sdf.parse(jTxtVreme.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Vreme nije uneto u ispravnom formatu!");
        }
        try {
            List<Sto> stolovi = Controller.getInstance().vratiStolove(vreme);
            for (Sto sto : stolovi) {
                jCBStolovi.addItem(sto);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void jBtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOdustaniActionPerformed
        try {
            Rezervacija r = new Rezervacija(sifraRezervacije, "", 0, new Date(), "");
            Controller.getInstance().obrisiRezervaciju(r);
        } catch (IOException ex) {
            Logger.getLogger(FRezervacija.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FRezervacija.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnOdustaniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDodajSto;
    private javax.swing.JButton jBtnIzbaciSto;
    private javax.swing.JButton jBtnOdustani;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBStolovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTxtAreaNapomena;
    private javax.swing.JTextField jTxtBrojMesta;
    private javax.swing.JTextField jTxtNaIme;
    private javax.swing.JTextField jTxtSifra;
    private javax.swing.JTextField jTxtStoMesto;
    private javax.swing.JTextField jTxtUkupno;
    private javax.swing.JTextField jTxtVreme;
    // End of variables declaration//GEN-END:variables

    private void popuniFormu() {
        model = new StoTableModel();
        jTable1.setModel(model);
        jTxtSifra.setText(sifraRezervacije + "");
        jCBStolovi.removeAllItems();
    }
    
    private void osveziUkupanBrojObezbedjenihMesta() {
        int obezbedjenaMesta = 0;
        List<Sto> stolovi = model.getStolovi();
        for (Sto s : stolovi) {
            obezbedjenaMesta = obezbedjenaMesta + s.getBrojMesta();
        }
        jTxtUkupno.setText(obezbedjenaMesta + "");
    }
    
    private Rezervacija validacija() {
        String naIme = jTxtNaIme.getText();
        String vreme = jTxtVreme.getText();
        String brojMesta = jTxtBrojMesta.getText();
        String Napomena = jTxtAreaNapomena.getText();
        String UkupnoMesta = jTxtUkupno.getText();
        
        if (naIme.isEmpty() || vreme.isEmpty() || brojMesta.isEmpty()) {
            throw new RuntimeException("Sva polja osim napomene moraju biti popunjena!");
        }
        Date vremeD = new Date();
        try {
            vremeD = new Date(sdf.parse(vreme).getTime());
        } catch (ParseException e) {
            throw new RuntimeException("Datum nije pravilno unet");
        }
        int brojMestaI = 0;
        try {
            brojMestaI = Integer.valueOf(brojMesta);
            if (brojMestaI <= 0) {
                throw new RuntimeException("Broj mesta mora biti pozitivan broj veci od nule!");
            }
        } catch (NumberFormatException e) {
            throw new RuntimeException("Unesite pravilno broj mesta (u formi broja)");
        }
        
        List<Sto> stolovi = model.getStolovi();
        
        if (stolovi.isEmpty()) {
            throw new RuntimeException("Morate dodeliti bar jedan sto!");
        }
        int ukupnoMestaI = Integer.valueOf(UkupnoMesta);
        if (ukupnoMestaI < brojMestaI) {
            throw new RuntimeException("Niste obezbedili dovoljno mesta za rezervaciju!");
        }
        
        Rezervacija rezervacija = new Rezervacija(sifraRezervacije, naIme, brojMestaI, vremeD, Napomena);
        rezervacija.setStolovi(stolovi);
        return rezervacija;
    }
    
    private void popuniFormu(Rezervacija r) {
        model = new StoTableModel();
        List<Sto> stolovi = r.getStolovi();
        for (Sto s : stolovi) {
            s.setStatus(Status.STARI);
        }
        model.setStolovi(r.getStolovi());
        jTable1.setModel(model);
        jTxtSifra.setText(sifraRezervacije + "");
        jTxtNaIme.setText(r.getNaIme());
        jTxtVreme.setText(sdf.format(r.getVreme()));
        jTxtBrojMesta.setText(r.getBrojMesta() + "");
        jTxtAreaNapomena.setText(r.getNapomena());
        jCBStolovi.removeAllItems();
    }
}
